######################################################################
# Automatically generated by qmake (3.0) Tue Apr 3 16:38:50 2018
######################################################################

TEMPLATE = app
TARGET = gps
INCLUDEPATH += .
QT += widgets network

# Input
HEADERS += client.hh
SOURCES += client.cc main.cc
